BookingTicket/Controllers/DetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookingTicket.Controllers
{
    public class DetailController : Controller
    {
        // GET: Detail
        public ActionResult Detail()
        {
            return View();
        }
    }
}

BookingTicket/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookingTicket.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BookingTicket/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookingTicket.Controllers
{
    public class MovieController : Controller
    {
        // GET: Movie
        public ActionResult Index()
        {
            return View();
        }
        
    }
        
}

BookingTicket/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookingTicket.Controllers
{
    public class TicketController : Controller
    {
        // GET: Ticket
        public ActionResult Movie()
           
        {
            return View();
        }

    }
}

BookingTicket/Views/Detail/Detail.cshtml
@{
    ViewBag.Title = "Detail";
}
<style>
    search-container button {
        
        padding: 6px 10px;
        margin-top: 8px;
        margin-right: 16px;
        background: #ddd;
        font-size: 17px;
        border: none;
        cursor: pointer;
        float: right;
    }
    btn{
        background-color: #04AA6D; /* Green */
        border: none;
        color: white;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
    }
   
</style>
<div>
    <h2>
        New Released Movies
    </h2>
   

</div>



<html>
<body>
    <table>
        <tr>
            <td style="padding-right: 80px">
                <img src="@Url.Content("~/Content/Images/avatar.jpg")" alt="Your Image" /><br />
             
                @*<a class="btn" href="https://www.w3schools.com/">Book Ticket</a>*@
                @Html.ActionLink("Book Ticket", "Movie", "Ticket", new { area = "" }, new { @class = "nav-link" })
            </td>

            <td style="padding-right: 80px">
                <img src="@Url.Content("~/Content/Images/aveng.jpg")" width="200" height="260" alt="Your Image" /><br/>
                @Html.ActionLink("Book Ticket", "Movie", "Ticket", new { area = "" }, new { @class = "nav-link" })

            </td>
            <td style="padding-right: 80px">
                <img src="@Url.Content("~/Content/Images/kgf.jpg")" width="200" height="260" alt="Your Image" /><br/>
                @Html.ActionLink("Book Ticket", "Movie", "Ticket", new { area = "" }, new { @class = "nav-link" })
            </td>
            <td style="padding-right: 80px">
                <img src="@Url.Content("~/Content/Images/sam.jpg")" width="200" height="260" alt="Your Image" /><br/>
                @Html.ActionLink("Book Ticket", "Movie", "Ticket", new { area = "" }, new { @class = "nav-link" })
            </td>
        </tr>
        <tr>
            <td style="padding-right: 80px">
                <img src="@Url.Content("~/Content/Images/pol.jpg")" width="200" height="260" alt="Your Image" /><br/>
                @Html.ActionLink("Book Ticket", "Movie", "Ticket", new { area = "" }, new { @class = "nav-link" })
            </td>
            <td style="padding-right: 80px">
                <img src="@Url.Content("~/Content/Images/wonka.jpg")" width="200" height="260" alt="Your Image" /><br/>
                @Html.ActionLink("Book Ticket", "Movie", "Ticket", new { area = "" }, new { @class = "nav-link" })
            </td>
            <td style="padding-right: 80px">
                <img src="@Url.Content("~/Content/Images/wish.jpg")" width="200" height="260" alt="Your Image" /><br/>
                @Html.ActionLink("Book Ticket", "Movie", "Ticket", new { area = "" }, new { @class = "nav-link" })
            </td>
            <td style="padding-right: 80px">
                <img src="@Url.Content("~/Content/Images/sab.jpg")" width="200" height="260" alt="Your Image" /><br/>
                @Html.ActionLink("Book Ticket", "Movie", "Ticket", new { area = "" }, new { @class = "nav-link" })
            </td>
        </tr>

    </table>
</body>
</html>

BookingTicket/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

BookingTicket/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

BookingTicket/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">Online Movie Ticket Booking</h1>
        <p class="lead">You can Book your ticket Here</p>
        @*<p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>*@
    </section>

    <!--<div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>-->
            @*<p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>*@
            <!--<p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">-->
            @*<h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>*@
</main>

BookingTicket/Views/Movie/Index.cshtml
@{
    ViewBag.Title = "Index";

}
<h1>Login Page</h1>
@using (Html.BeginForm())
{
    <div>
        UserName : @Html.TextBox("UserName")

    </div>
    <div>
        Password : @Html.Password("Password")

    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <!-- Replace the submit button with an anchor tag -->
            @Html.ActionLink("Next", "Detail", "Detail", null, new { @class = "btn btn-primary" })
        </div>
    </div>
}

BookingTicket/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
   
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>

                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @RenderSection("ControlsSection", required: false)
</body>
</html>

BookingTicket/Views/Ticket/Movie.cshtml
@{
    ViewBag.Title = "Movie";
}

<h2>Booking Details</h2>

<div>
        <p><b>Personal Details</b></p>
        <form>
            <label for="fname">First name:</label>
            <input type="text" id="fname" name="fname"><br>
            <label for="lname">Last name:</label>
            <input type="text" id="lname" name="lname"><br />
            <label for="Pnum">Phone number:</label>
            <input type="text" id="num" name="number" /><br />
        </form>
    </div>
@using Syncfusion.EJ2
@using Syncfusion.EJ2.Maps
@section ControlsSection{
    <div class="col-lg-9 control-section">
        <div style="width:200px;margin:auto;padding-bottom:20px">
           
            <div style="padding-left:30px;font-size:20px;font-weight:400;"> seat selection</div>
        </div>
        <div style="border: 3px solid darkgray;width:200px;display:block;margin:auto;border-radius:5px">
            
            <div style="text-align:center">
                <div id="container"></div>
                @Html.EJS().Maps("container").ProjectionType(Syncfusion.EJ2.Maps.ProjectionType.Equirectangular).Load("mapsLoad").ItemSelection("itemSelection").Layers(layer =>
                 {
                     layer.GeometryType(Syncfusion.EJ2.Maps.GeometryType.Normal).ShapeSettings(new MapsShapeSettings { ColorValuePath = "fill" }).SelectionSettings(new MapsSelectionSettings { Enable = true, Opacity = 1, EnableMultiSelect = true }).ShapeData(ViewBag.shapeData).Add();
                 }).Render()
            </div>
        </div>
    </div>
    <div class="col-lg-3 property-section">
        <table id="property" title="Seat Selection" style="width: 100%;font-weight:400 !important">
            <tbody>
                <tr style="height: 30px">
                    <td>
                        <div style="height:0;width:15px;padding-bottom:5px;background-color:gray;border-radius:25%"></div>
                        <div id="available" style="margin-top: -25px;margin-left: 15px">
                            Available
                        </div>
                    </td>
                </tr>
                <tr style="height: 30px">
                    <td>
                        <div style="height:0;width:15px;padding-bottom:5px;background-color:Green;border-radius:25%"></div>
                        <div id="selected" style="margin-top: -25px;margin-left: 15px">
                            Selected
                        </div>
                    </td>
                </tr>
                <tr style="height: 30px">
                    <td>
                        <div style="height:0;width:15px;padding-bottom:5px;background-color:Orange;border-radius:25%"></div>
                        <div id="booked" style="margin-top: -25px;margin-left: 15px">
                            Booked
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <div id="seat-parent">
        <span id="clear-btn">Clear Selection</span><br><br>
        <div id="selectedseats"></div>
    </div>
    <style>
        #control-container {
            padding: 0px !important;
        }

        #seat-parent {
            text-align: center;
            cursor: pointer;
        }

        #selectedseats {
            padding: 10px;
        }

        #selectedseats, #seat-info {
            font-size: 14px;
        }

        #clear-btn {
            padding: 10px;
            border: 2px solid rgb(241, 235, 247);
            border-radius: 8px;
            background: rgb(246, 245, 248);
            color: black;
            font-size: 14px;
        }

        .seats {
            padding-top: 15px;
            font-weight: bold;
        }
    </style>
    <script>
        var seatInfo = document.getElementById('selectedseats');
        function mapsLoad(args) {
            var theme = themeName ? themeName : 'Material';
            args.maps.theme = (theme.charAt(0).toUpperCase() + theme.slice(1)).replace(/-dark/i, "Dark").replace(/contrast/i, 'Contrast');
        }
        function itemSelection(args) {
            if (args.shapeData.fill === 'Orange') {
                args.fill = 'Orange !important';
                document.getElementById(args.target).setAttribute('class', 'ShapeselectionMapStyle');
                return;
            }
            args.fill = 'green';
            var seat = args.shapeData.seatno;
            var connector = ' ';
            if (seatInfo.innerHTML === '') {
                seatInfo.innerHTML = '<span id="seat-info">Seats Selected -</span>';
            }
            else {
                connector = ', ';
            }
            var seatString = '<span class="seats">' + connector + seat + '</span>';
            var seatString1 = ' ' + seat + '</span><span class="seats">,';
            var lastString = '<span id="seat-info">Seats Selected -</span><span class="seats"> ' + seat + '</span>';
            if (seatInfo.innerHTML.indexOf(seatString) === -1 && seatInfo.innerHTML.indexOf(seatString1) === -1 &&
                seatInfo.innerHTML.indexOf(lastString) === -1) {
                seatInfo.innerHTML += '<span class="seats">' + connector + seat + '</span>';
            }
            else {
                seatInfo.innerHTML = seatInfo.innerHTML.replace(seatString, '');
                seatInfo.innerHTML = seatInfo.innerHTML.replace(seatString1, '');
                if (seatInfo.innerHTML === lastString) {
                    seatInfo.innerHTML = '';
                }
            }
        }
        document.getElementById('clear-btn').onclick = function () {
            seatInfo.innerHTML = '';
            var selected = document.getElementsByClassName('ShapeselectionMapStyle');
            for (var i = 0, length_1 = selected.length; i < length_1; i++) {
                selected[0].setAttribute('class', '');
            }
        };
    </script>

}